### ISSUE TITLE
Пофиксить левую навигацию для IE11

### ISSUE THREAD

**Issue by dimy4** [plentylions/modellversum#1]
![modellversum-nav](https://user-images.githubusercontent.com/2969266/49447548-1eb4e100-f7d7-11e8-8c29-3ccd9289c1e7.jpg)

**Comment by mshYat** [comment]
готово

**Comment by dimy4** [comment]
Стало лучше но не совсем всё. 
Текст нужно выровнять по центру по вертикале
![unbenannt-2345](https://user-images.githubusercontent.com/2969266/49455357-5592f300-f7e7-11e8-8d4b-46328ea595bd.jpg)

**Comment by mshYat** [comment]
готово
