### ISSUE TITLE
На стр. продукта в галерее использовать картинки среднего размера

### ISSUE THREAD

**Issue by dimy4** [plentylions/modellversum#2]
На форуме есть пример как это делается
https://forum.plentymarkets.com/t/ceres-bildgroesse-artikeldetailseite/506536/3

**Comment by mshYat** [comment]
готово

**Comment by dimy4** [comment]
только картинку среднего размера. Линк оставить на большую (для попапа)

**Comment by mshYat** [comment]
неактуально
