### ISSUE TITLE
Убрать фиксированную высоту с галереи продукта

### ISSUE THREAD

**Issue by dimy4** [plentylions/modellversum#3]
Должно получится так:
![image](https://user-images.githubusercontent.com/2969266/50241634-4788c900-03c8-11e9-9b46-257330bf4030.png)
https://www.modellversum.com/autos-und-nutzfahrzeuge-cars/fertigmodelle/sonstiges/maerklin-h0-hymer-wohnmobil-looney-tunes-aus-1-fc-maerklin-jahreswagen-48611-neu_3002024_16791

**Comment by mshYat** [comment]
готово
